CREATE USER xnat  NOCREATEDB;
CREATE DATABASE xnat OWNER xnat;
ALTER USER xnat WITH PASSWORD 'xnat';
CREATE USER orthanc  NOCREATEDB;
CREATE DATABASE orthanc OWNER orthanc;
ALTER USER orthanc WITH PASSWORD 'orthanc';