name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build images for nginx, web and db
        run: |
          XNAT_NGINX_IMAGE=docker.io/xnat-docker-compose/xnat_docker_compose_xnat-nginx:${{ github.sha }} docker-compose build xnat-nginx
          XNAT_WEB_IMAGE=docker.io/xnat-docker-compose/xnat_docker_compose_xnat-web:${{ github.sha }} docker-compose build xnat-web
          XNAT_DB_IMAGE=docker.io/xnat-docker-compose/xnat_docker_compose_xnat-db:${{ github.sha }} docker-compose build xnat-db

      - name: Create folder for the scanner results
        run: mkdir results

      - name: Run Trivy vulnerability scanner on nginx
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/xnat-docker-compose/xnat_docker_compose_xnat-nginx:${{ github.sha }}'
          # format: 'table'
          # exit-code: '1'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: './results/trivy-results-nginx.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        # continue-on-error: true

      - name: Run Trivy vulnerability scanner on web
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/xnat-docker-compose/xnat_docker_compose_xnat-web:${{ github.sha }}'
          # format: 'table'
          # exit-code: '1'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: './results/trivy-results-web.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        # continue-on-error: true

      - name: Run Trivy vulnerability scanner on postgres
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/xnat-docker-compose/xnat_docker_compose_xnat-db:${{ github.sha }}'
          # format: 'table'
          # exit-code: '1'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: './results/trivy-results-db.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: './results'
